### ISSUE TITLE
Graphical issues using RLTK on Linux

### ISSUE THREAD

**Issue by uzkbwza** [thebracket/rltk_rs#8]
Hey there. I want to use this library, but it seems to have graphical artifacts on Linux. I have tried using it on both my laptop and desktop PCs, which have different graphics cards and all drivers installed. Just wondering if there's an easy fix for this before i try to jump into figuring it out myself 
![screenshot](https://user-images.githubusercontent.com/43023911/65367546-b1e4c900-dbe7-11e9-9b28-3bae95559a08.png)

**Comment by thebracket** [comment]
That's an odd one. It looks like a scaling issue. I really need to get a Linux box to test on - most of the reported issues so far have been on Linux!

If I had to hazard a guess, it's related to the handling on RESIZE events (https://github.com/thebracket/rltk_rs/blob/master/src/platform_specific.rs, around line 145). There's some code that got commented out to assist with a *different* Linux problem (it calls resize a lot more than you'd expect, when the window decorations are added to the window). The hard part is finding the magical incantation that goes there...

**Comment by thebracket** [comment]
It definitely relates to resizing the window. I found and fixed a similar problem under `wasm`, if I didn't resize the canvas. I'm setting up a Linux VM right now (limited time available; moving house) and hope to have this fixed Mon/Tue.

**Comment by thebracket** [comment]
I've merged in some changes that resolved the issue in a VM running Ubuntu Linux.

**Comment by vokar** [comment]
Unfortunately, I still have the artifacts. Which additional data may be useful to you?

**Comment by thebracket** [comment]
What window manager are you using (I'm assuming on X11)? I've been testing on the default one that Ubuntu installs.

**Comment by vokar** [comment]
Tested on [i3wm](https://i3wm.org/) and [dwm](https://dwm.suckless.org/): both are for X11 and both have the problem.

**Comment by thebracket** [comment]
![image](https://user-images.githubusercontent.com/14896751/66346121-1194e100-e917-11e9-97a2-5fe198af1a95.png)

Is what I see on dwm (I didn't have i3wm handy). Never used that particular WM before, so it's pretty much on the package defaults. Other than everything being slow in my VM, it looks ok.

I'll do some more digging and see what I can find. I have a suspicion that Glutin (the GL library) is trying to do something "clever" with its DPI handling support, and blowing things up as a result.

**Comment by thebracket** [comment]
The good news is that I can now replicate this issue by resizing the viewport when the window changes and deliberately picking inappropriate sizes. It'll take me a bit to get an actual fix in place, but I've now got a good handle on what's going on. :-)

**Comment by vokar** [comment]
Hurray! Looks like 9441dbe actually solves the problem. Thank you!
